### PR TITLE
feat: Add support for `with.token`

### LINKED ISSUE #104: Support `with.token`
The most used first-party `actions/checkout` action uses the cleaner `token` input instead of the 60s-like `GITHUB_TOKEN`

https://github.com/actions/checkout#usage

Can this also automatically support `with.token` instead of just `GITHUB_TOKEN`?

```yml
steps:
  - name: My action
    with:
      token: ${{ secrets.GITHUB_TOKEN }}
```

### PR DESCRIPTION
**Pull request by fregante**
Fixes #104

### CODE REVIEW

**Comment by fregante** [comment]
The readme always calls it "the `GITHUB_TOKEN` variable" so I'm treating the support for `with.token` as an additional way of doing things, both in the readme and in the error messages. 

The alternative would be to replace most references to `GITHUB_TOKEN` with a more generic "the token variable" instead and rewrite a bit more of the readme. Let me know if you prefer that.

**Comment by gr2m** [comment]
That works, thank you! One thing I would add is to add a test for the edge case when both are set: `INPUT_GITHUB_TOKEN` and `INPUT_TOKEN`. I would give `INPUT_GITHUB_TOKEN` preference, and document that behavior in the README, too

**Comment by fregante** [comment]
Why give a preference? Currently if any 2 keys are used, it just doesn’t work, just like before

**Comment by gr2m** [comment]
You are right, I forgot about that 👍🏼

**Review by gr2m — APPROVED** [review]

**Pull request merged**
