### PR TITLE
feat: add kebab-case support `with.github-token`

### LINKED ISSUE #318: [FEAT]: Support `with.github-token` (kebab-case)
### Describe the need

Following up https://github.com/octokit/auth-action.js/issues/104

A few first-party actions like:
- https://github.com/actions/add-to-project/blob/main/src/add-to-project.ts#L38
- https://github.com/actions/github-script/blob/main/src/main.ts#L27

uses kebab-case style for github token, on the community side much more ;)

Nice to have `with.github-token` support instead of only `with.token` or `with.github_token`, like:

```yaml
steps:
  - name: My action
    with:
      github-token: ${{ github.token }}
```

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by DariuszPorowski**
Resolves #318

----

### Before the change?

* no support for kebab-case style for github token using `with`

### After the change?

* add kebab-case style support `with.github-token`

### Other information

* N/A

----

### Pull request checklist
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Added the appropriate label for the given change `no permission to do it ;)`

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [X] No

If `Yes`, what's the impact:

* N/A

### Pull request type

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Review by gr2m — APPROVED** [review]
Looks good, cheers 👍🏼

**Comment by gr2m** [comment]
Can you run `npm run lint:fix` to fix the linting errors? I don't seem to have write access to your fork, otherwise I'd have done it myself

**Comment by DariuszPorowski** [comment]
@gr2m hmm, interesting because PR is marked `Allow edits by maintainers` whatever... lint done :)

**Comment by gr2m** [comment]
> @gr2m hmm, interesting because PR is marked `Allow edits by maintainers` whatever... lint done :)

probably my fault then. I used codespace on your fork, it wouldn't let me push 🤷🏼 Anyway, cheers1

**Comment by gr2m** [comment]
Sorry it looks like it introduced a regression for users of github-script. Until we figure out what, I'll have to revert this change. See https://github.com/octokit/auth-action.js/pull/321

**Comment by DariuszPorowski** [comment]
@gr2m just figured out:
`actions/github-script` uses `with.github-token` by default: https://github.com/actions/github-script/blob/main/action.yml#L11

so, I assume that the intention of the creators of the `actions/github-script` action is to use this for the tokens: ref: https://github.com/actions/github-script/tree/main#using-a-separate-github-token
`actions/github-script` is already pre-authenticated with Octokit using mentioned method: https://github.com/actions/github-script/blob/main/README.md?plain=1#L13
The issue https://github.com/octokit/auth-action.js/issues/320 contains the code that does new own Octokit instance, which was probably not in line with the action's assumptions. Regardless of that, it's still possible but token should be utilized in the `actions/github-script` way like:
`process.env['INPUT_GITHUB-TOKEN']` or using `@actions/core` (already include in this action): `const token = core.getInput('github-token')`

**Comment by gr2m** [comment]
how about this: instead of adding support for the `github-token`, we throw a helpful error message if neither `token` nor `github_token` is set, but `github-token` is?

**Comment by DariuszPorowski** [comment]
@gr2m sounds like kind of workaround... but before we jump into... just saw `actions/github-script` does not use `@octokit/auth-action` at all 😸 so it's a not root cause for https://github.com/octokit/auth-action.js/issues/320. Example from this issue uses `const { Octokit } = require("@octokit/action")` so it utilize `@octokit/action` and it uses `@octokit/auth-action`. But even with that it's not a problem.
Problem starts when someone use `@octokit/action` inside `actions/github-script` and want to use own token in a different way that `actions/github-script` expose. Why? because `actions/github-script` already handle the token in `with.github-token` so it already inside the script, and `@octokit/action` can access it via `@octokit/auth-action` (assuming my PR is already there).
Going deeper, latest release of `@octokit/action` does not contain `@octokit/auth-action` v2.1.0 yet, so it should not fail (unless someone independently installs the latest `@octokit/auth-action` package)

**Comment by gr2m** [comment]
Ahh I see. Yeah the way `@TCarrol` import `@octokit/action` in the script is odd, as that's what the action does by default with the global `github`. I'll let them now

**Comment by DariuszPorowski** [comment]
Use case for `@octokit/action` what I see it's a bit different (https://github.com/octokit/action.js/blob/main/README.md?plain=1#L50) and makes sense, but `@octokit/action` inside `actions/github-script` looks like unnecessary overlap.

**Comment by DariuszPorowski** [comment]
Hey @gr2m just following up, do you think is it ok to reopen this pr?

**Pull request merged**
